config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :trophies

  map.resources :games, :collection => { :played => :get }, :member => { :select_players => :get, :select_trophies => :get } do |game|
    game.resources :trophy_games, :member => { :select_players => :get }
  end

  map.resources :players

  

  map.root :controller => "players"

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :player_games
  has_many :players, :through => :player_games
  has_many :trophy_games
  has_many :trophies, :through => :trophy_games
end

app/models/participation.rb
class Participation < ActiveRecord::Base
  belongs_to :player
  belongs_to :trophy_game
end

app/models/player.rb
class Player < ActiveRecord::Base
  validates_presence_of :name, :nick

  has_many :player_games
  has_many :games, :through => :player_games
  has_many :participations
  has_many :trophy_games, :through => :participations

  attr_reader :complete_name

  def complete_name
    return "#{self.name} #{self.surname} <em>#{self.nick}</em>"
  end

end

app/models/player_game.rb
class PlayerGame < ActiveRecord::Base
  belongs_to :player
  belongs_to :game
end

app/models/trophy.rb
class Trophy < ActiveRecord::Base
  validates_presence_of :title

  has_many :trophy_games
  has_many :games, :through => :trophy_games

  attr_reader :complete_title

  def complete_title
    return "Trophy \"#{self.title}\""
  end
end

app/models/trophy_game.rb
class TrophyGame < ActiveRecord::Base
  belongs_to :trophy
  belongs_to :game

  has_many :participations
  has_many :players, :through => :participations
end

app/controllers/application_controller.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time
  protect_from_forgery # See ActionController::RequestForgeryProtection for details

  # Scrub sensitive parameters from your log
  # filter_parameter_logging :password
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  def index
    @games = Game.all(:conditions => {:played => false})

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /games/played
  def played
    @games = Game.all(:conditions => {:played => true})

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /games/1
  def show
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /games/new
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        flash[:notice] = 'Game was successfully created.'
        format.html { redirect_to path_after_success }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /games/1
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        flash[:notice] = 'Game was successfully updated.'
        format.html { redirect_to path_after_success }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /games/1
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to path_after_success }
    end
  end

  # GET /games/1/select_players
  def select_players
    @game = Game.find(params[:id])
    @players = Player.all(:order => :name)
  end

  # GET /games/1/select_trophies
  def select_trophies
    @game = Game.find(params[:id])
    @trophies = Trophy.all(:order => :title)
  end

  private

  def path_after_success
    games_url
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # GET /players
  def index
    @players = Player.all(:order => :name)

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /players/1
  def show
    @player = Player.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /players/new
  def new
    @player = Player.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # POST /players
  def create
    @player = Player.new(params[:player])

    respond_to do |format|
      if @player.save
        flash[:notice] = 'Player was successfully created.'
        format.html { redirect_to path_after_success }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /players/1
  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        flash[:notice] = 'Player was successfully updated.'
        format.html { redirect_to path_after_success }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /players/1
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to path_after_success }
    end
  end

  private

  def path_after_success
    players_url
  end
end

app/controllers/trophies_controller.rb
class TrophiesController < ApplicationController
  # GET /trophies
  def index
    @trophies = Trophy.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /trophies/1
  def show
    @trophy = Trophy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /trophies/new
  def new
    @trophy = Trophy.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /trophies/1/edit
  def edit
    @trophy = Trophy.find(params[:id])
  end

  # POST /trophies
  def create
    @trophy = Trophy.new(params[:trophy])

    respond_to do |format|
      if @trophy.save
        flash[:notice] = 'Trophy was successfully created.'
        format.html { redirect_to path_after_success }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /trophies/1
  def update
    @trophy = Trophy.find(params[:id])

    respond_to do |format|
      if @trophy.update_attributes(params[:trophy])
        flash[:notice] = 'Trophy was successfully updated.'
        format.html { redirect_to path_after_success }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /trophies/1
  def destroy
    @trophy = Trophy.find(params[:id])
    @trophy.destroy

    respond_to do |format|
      format.html { redirect_to path_after_success }
    end
  end

  private

  def path_after_success
    trophies_url
  end

end

app/controllers/trophy_games_controller.rb
class TrophyGamesController < ApplicationController

  # GET /games/1/trophy_games
  def index
    @game = Game.find(params[:game_id])
    @trophy_games = TrophyGame.all(:conditions => { :game_id => params[:game_id] })
    #@players_that_no_played = Player.all(:order => :name)
  end

  # GET /games/1/trophy_games/1/select_players
  def select_players
    @game = Game.find(params[:game_id])
    @trophy_game = TrophyGame.find(params[:id])
    @players = Player.all(:order => :name)
  end

  # PUT /games/1/trophy_games/1
  def update
    @game = Game.find(params[:game_id])
    @trophy_game = TrophyGame.find(params[:id])

    respond_to do |format|
      if @trophy_game.update_attributes(params[:trophy_game])
        flash[:notice] = "OK"
        format.html { redirect_to select_players_game_trophy_game_path(@game,@trophy_game) }
      else
        flash[:notice] = "Error"
        format.html { render :action => "select_players" }
      end
    end
  end

end

app/helpers/application_helper.rb
# Methods added to this helper will be available to all templates in the application.
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/trophies_helper.rb
module TrophiesHelper
end

app/helpers/trophy_games_helper.rb
module TrophyGamesHelper
end

app/views/games/_form.html.erb
<%
if action_name == "new" or action_name == "create"
  title = "New game"
  save = "Create"
else
  title = "Editing game"
  save = "Update"
end
%>
<h1><%= title %></h1>

<% form_for(@game) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :date %> and <%= f.label "time", :time %><br />
    <%= f.date_select :date %> - 
    <%= f.time_select :time, :options => {:default => "19:00"} %>
  </p>
  <p>
    <%= f.check_box :played %>
    <%= f.label :played %>
  </p>
  <p>
    <%= f.submit save %>
  </p>
<% end %>

app/views/games/_games.html.erb
<h1>Listing games</h1>

<% if !@games.empty? %>

<table>
  <tr>
    <th>Date and time</th>
    <th>Played</th>
    <th colspan="3" class="actions">Actions</th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%=h game.date %> (<%=h game.time %>)</td>
    <td><%=h game.played %></td>
    <% if game.played %>
      <td><%= link_to 'Select players', select_players_game_path(game) %></td>
      <td><%= link_to 'Select trophies', select_trophies_game_path(game) %></td>
      <td><%= link_to 'Select players for trophies', game_trophy_games_path(game) %></td>
    <% else %>
      <td colspan="2"><%= link_to 'Edit', edit_game_path(game) %></td>
      <td><%= link_to 'Destroy', game, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

  <% else %>
    <p>There is no games. <%= link_to "Add the first!", new_game_path %></p>

<% end %>

app/views/games/index.html.erb
<%= render :partial => "games" %>

app/views/games/played.html.erb
<%= render :partial => "games" %>

app/views/games/select_players.html.erb
<h1>Game played <%= @game.date %> - <%= @game.time %></h1>
<p>Choose who played this game:</p>
<% form_for(@game) do |f| %>
  <ul>
    <% @players.each do |player| %>
      <li><label><%= check_box_tag("game[player_ids][]", player.id, @game.players.include?(player)) %> <%= player.complete_name %></label></li>
    <% end %>
  </ul>
  <p>
    <%= f.submit "Save" %>
  </p>
<% end %>

app/views/games/select_trophies.html.erb
<h1>Game played <%= @game.date %> - <%= @game.time %></h1>
<p>Choose trophies for this game:</p>
<% form_for(@game) do |f| %>
  <ul>
    <% @trophies.each do |trophy| %>
      <li><label><%= check_box_tag("game[trophy_ids][]", trophy.id, @game.trophies.include?(trophy)) %> <%= trophy.complete_title %></label></li>
    <% end %>
  </ul>
  <p>
    <%= f.submit "Save" %>
  </p>
<% end %>

app/views/games/show.html.erb
<p>
  <b>Date:</b>
  <%=h @game.date %>
</p>

<p>
  <b>Time:</b>
  <%=h @game.time %>
</p>

<p>
  <b>Played:</b>
  <%=h @game.played %>
</p>


<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<?xml version="1.0"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <meta http-equiv="content-language" content="en" />
  <meta name="robots" content="noindex,nofollow" />
  <%= stylesheet_link_tag "adminiziolite/css/reset", :media => "screen, projection" %><!-- RESET -->
  <%= stylesheet_link_tag "adminiziolite/css/main", :media => "screen, projection" %><!-- MAIN STYLE SHEET -->
  <%= stylesheet_link_tag "adminiziolite/css/2col", :media => "screen, projection" %><!-- DEFAULT: 2 COLUMNS -->
  <%= stylesheet_link_tag "adminiziolite/css/1col", :media => "screen, projection", :rel => "stylesheet, alternate" %><!-- ALTERNATE: 1 COLUMN -->
  <!--[if lte IE 6]><%= stylesheet_link_tag "adminiziolite/css/main-ie6", :media => "screen, projection" %><![endif]--><!-- MSIE6 -->
  <%= stylesheet_link_tag "adminiziolite/css/style", :media => "screen, projection"  %><!-- GRAPHIC THEME -->
  <%= stylesheet_link_tag "adminiziolite/css/mystyle", :media => "screen, projection"  %><!-- WRITE YOUR CSS CODE HERE -->
  <%= javascript_include_tag "adminiziolite/js/jquery" %>
  <%= javascript_include_tag "adminiziolite/js/switcher" %>
  <%= javascript_include_tag "adminiziolite/js/toggle" %>
  <%= javascript_include_tag "adminiziolite/js/ui.core" %>
  <%= javascript_include_tag "adminiziolite/js/ui.tabs" %>
  <script type="text/javascript">
  $(document).ready(function(){
          $(".tabs > ul").tabs();
  });
  </script>
  <title>mahou</title>
</head>
<body>

<div id="main">

	<!-- Tray -->
	<div id="tray" class="box">
		<p class="f-left box">
                  <strong><%= link_to "inicio", root_path %></strong>
		</p>
		<p class="f-right"></p>
	</div> <!--  /tray -->
	<hr class="noscreen" />
	<!-- Menu -->
          <%#= render :partial => "shared/menu", :class => "box", :locals => {:id => "menu", :active => "menu-active"} %>
	<hr class="noscreen" />
	<!-- Columns -->
	<div id="cols" class="box">
		<!-- Aside (Left Column) -->
		<div id="aside" class="box">
			<div class="padding box">
			</div> <!-- /padding -->
                        <%= render :partial => "shared/submenu", :class => "box", :locals => {:active => "submenu-active"} %>
		</div> <!-- /aside -->
		<hr class="noscreen" />
		<!-- Content (Right Column) -->
		<div id="content" class="box">
                  <% unless flash[:notice].nil? %>
                    <p class="msg done"><%= flash[:notice] %></p>
                  <% end %>
                  <% unless flash[:warning].nil? %>
                    <p class="msg warning"><%= flash[:warning] %></p>
                  <% end %>
                  <% unless flash[:error].nil? %>
                    <p class="msg error"><%= flash[:error] %></p>
                  <% end %>
                  <%= yield %>
		</div> <!-- /content -->
	</div> <!-- /cols -->
	<hr class="noscreen" />
	<!-- Footer -->
	<div id="footer" class="box">
          <p class="f-left"><%= link_to "sergiogomez", "http://github.com/sergiogomez/" %></p>
          <p class="f-right">templates by <a href="http://www.adminizio.com/">Adminizio</a></p>
	</div> <!-- /footer -->
</div> <!-- /main -->
</body>
</html>

app/views/players/_form.html.erb
<%
if action_name == "new" or action_name == "create"
  title = "New player"
  save = "Create"
else
  title = "Editing player"
  save = "Update"
end
%>
<h1><%= title %></h1>

<% form_for(@player) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :surname %><br />
    <%= f.text_field :surname %>
  </p>
  <p>
    <%= f.label :nick %><br />
    <%= f.text_field :nick %>
  </p>
  <p>
    <%= f.submit save %>
  </p>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<% form_for(@player) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :surname %><br />
    <%= f.text_field :surname %>
  </p>
  <p>
    <%= f.label :nick %><br />
    <%= f.text_field :nick %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<% if !@players.empty? %>

  <table>
    <tr>
      <th>Player</th>
      <th colspan="2" class="actions">Actions</th>
    </tr>

  <% @players.each do |player| %>
    <tr>
      <td><%=h player.name %> <%=h player.surname %> "<em><%=h player.nick %></em>"</td>
      <td><%= link_to 'Edit', edit_player_path(player) %></td>
      <td><%= link_to 'Delete', player, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
  </table>

  <% else %>
    <p>There is no players. <%= link_to "Add the first!", new_player_path %></p>

<% end %>

app/views/players/show.html.erb
<p>
  <b>Name:</b>
  <%=h @player.name %>
</p>

<p>
  <b>Surname:</b>
  <%=h @player.surname %>
</p>

<p>
  <b>Nick:</b>
  <%=h @player.nick %>
</p>


<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/shared/_menu.html.erb
<div id="<%= id %>" class="<%= :class %>">
  <ul class="<%= :class %>">
    <li id="<%= active %>"><%= link_to (content_tag("span","Players"), players_path) %></li> <!-- Active -->
  </ul>
</div> <!-- /header -->

app/views/shared/_submenu.html.erb
<ul class="<%= :class %>">
  <li><%= link_to "Players", players_path %></li>
  <li><%= link_to "Next games", games_path %></li>
  <li><%= link_to "Played games", played_games_path %></li>
  <li><%= link_to "Trophies", trophies_path %></li>
  <li><%= link_to "New player", new_player_path %></li>
  <li><%= link_to "New game", new_game_path %></li>
  <li><%= link_to "New trophy", new_trophy_path %></li>
</ul>

app/views/trophies/_form.html.erb
<%
if action_name == "new" or action_name == "create"
  title = "New trophy"
  save = "Create"
else
  title = "Editing trophy"
  save = "Update"
end
%>
<h1><%= title %></h1>

<% form_for(@trophy) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit save %>
  </p>
<% end %>

app/views/trophies/edit.html.erb
<%= render :partial => "form" %>

app/views/trophies/index.html.erb
<h1>Listing trophies</h1>

<% if !@trophies.empty? %>

<table>
  <tr>
    <th>Trophy</th>
    <th>Description</th>
    <th>Game count (future)</th>
    <th colspan="2" class="actions">Actions</th>
  </tr>

<% @trophies.each do |trophy| %>
  <tr>
    <td><%=h trophy.complete_title %></td>
    <td><%=h trophy.description %></td>
    <td><em>-</em></td>
    <td><%= link_to 'Edit', edit_trophy_path(trophy) %></td>
    <td><%= link_to 'Destroy', trophy, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

  <% else %>
    <p>There is no trophies. <%= link_to "Add the first!", new_trophy_path %></p>

<% end %>

app/views/trophies/new.html.erb
<%= render :partial => "form" %>

app/views/trophies/show.html.erb
<p>
  <b>Title:</b>
  <%=h @trophy.title %>
</p>

<p>
  <b>Description:</b>
  <%=h @trophy.description %>
</p>


<%= link_to 'Edit', edit_trophy_path(@trophy) %> |
<%= link_to 'Back', trophies_path %>

app/views/trophy_games/index.html.erb
<h1>Game played <%= @game.date %> - <%= @game.time %></h1>
<p>First choose trophy from this game:</p>
  <ul>
    <% @trophy_games.each do |trophy_game| %>
      <li><%= link_to trophy_game.trophy.complete_title, select_players_game_trophy_game_path(@game,trophy_game) %></li>
    <% end %>
  </ul>

app/views/trophy_games/select_players.html.erb
<h1>Game played <%= @game.date %> - <%= @game.time %></h1>
<h2><%= @trophy_game.trophy.complete_title %></h2>
<p>Choose who can win this trophy:</p>
<% form_for([@game, @trophy_game]) do |f| %>
  <ul>
    <% @players.each do |player| %>
      <li><label><%= check_box_tag("trophy_game[player_ids][]", player.id, @trophy_game.players.include?(player)) %> <%= player.complete_name %></label></li>
    <% end %>
  </ul>
  <p>
    <%= f.submit "Save" %>
  </p>
<% end %>
<p><%= link_to "Back to trophies for the game", game_trophy_games_path(@game) %></p>